name: Scraper Rugby isquad

on:
  schedule:
    - cron: '0 20 * * 0' # Se ejecuta los domingos a las 20:00 UTC
  workflow_dispatch: # Botón manual

  # ESTO ES LO QUE SOLUCIONA EL ERROR 128
permissions:
  contents: write

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar Scraper
        run: python scripts/scrape.py

      - name: Guardar los JSON en GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Actualización de resultados" || echo "No hay cambios para subir"
          git push
